### PR TITLE
src: custom: bluerov: Deal when there is no valid size available

### PR DESCRIPTION
**Pull request by patrickelectric**
This is for a bug fix for 3.3 used by BlueOS 1.0

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
@patrickelectric Check the linter

**Comment by patrickelectric** [comment]
> @patrickelectric Check the linter

It appears that there is also problem with the build process related to some linux dependencies

**Comment by joaoantoniocardoso** [comment]
@patrickelectric Can you rebase it over master?

**Comment by patrickelectric** [comment]
Replaced by: https://github.com/bluerobotics/mavlink-camera-manager/pull/196

**Pull request closed without merging**
